// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWEDLYgHTbAL48PFIJbaLL30xwemvmZA',
    appId: '1:275601413886:web:e5851c952e26f94b86b7af',
    messagingSenderId: '275601413886',
    projectId: 'test-project-90ad6',
    authDomain: 'test-project-90ad6.firebaseapp.com',
    storageBucket: 'test-project-90ad6.appspot.com',
    measurementId: 'G-J1JX3YQGZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC00VwA8EwXhqMqlnMLJytIYSUEfVPKwdI',
    appId: '1:275601413886:android:63013fdc2a17b40886b7af',
    messagingSenderId: '275601413886',
    projectId: 'test-project-90ad6',
    storageBucket: 'test-project-90ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDChGQxM7DKlydy9dGKqr0UaXoJr9m3it4',
    appId: '1:275601413886:ios:9e754b99452c00c086b7af',
    messagingSenderId: '275601413886',
    projectId: 'test-project-90ad6',
    storageBucket: 'test-project-90ad6.appspot.com',
    iosClientId: '275601413886-7su6o95e6lq44hq9pcvbhiaflvpogv66.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );
}
